/* eslint-disable */
/**
 * This file was automatically generated by bee-bapi-to-ts.
 * DO NOT MODIFY IT BY HAND.
 */
import axios, { type RequestConfig } from './request';

import type {
  GetMetrics,
  PostVoltronCommentCreate,
  PostVoltronCommentDelete,
  GetVoltronCommentDetail,
  PostVoltronCommentList,
  PostVoltronCommentUpdate,
  GetVoltronCommonDeptTree,
  GetVoltronCommonDict,
  PostVoltronCommonEmployeeKeyword,
  PostVoltronCommonProxy,
  PostVoltronCommonProxyMulti,
  GetVoltronCommonUserInfo,
  GetVoltronDeveloperAnalyzeRepositories,
  GetVoltronDeveloperRepositoriesBranches,
  GetVoltronDeveloperRepositoriesTree,
  GetVoltronDeveloperSchemasComponent,
  GetVoltronMaterial,
  PostVoltronMaterial,
  GetVoltronMaterialProp,
  PostVoltronMaterialProp,
  DeleteVoltronMaterialPropById,
  GetVoltronMaterialPropById,
  PatchVoltronMaterialPropById,
  PostVoltronMaterialPropBatchDelete,
  GetVoltronMaterialPropMaterialByMaterialId,
  DeleteVoltronMaterialById,
  GetVoltronMaterialById,
  PatchVoltronMaterialById,
  DeleteVoltronMaterialFullById,
  GetVoltronMaterialFullById,
  DeleteVoltronMaterialPackage,
  GetVoltronMaterialPackage,
  GetVoltronMaterialPackages,
  PatchVoltronMaterialPropsBatch,
  PostVoltronModuleCreate,
  PostVoltronModuleDelete,
  GetVoltronModuleList,
  GetVoltronModuleListAll,
  PostVoltronModuleUpdate,
  GetVoltronNavigationList,
  PostVoltronNavigationUpdate,
  PostVoltronNoteCreate,
  PostVoltronNoteDelete,
  GetVoltronNoteList,
  PostVoltronNoteUpdate,
  PostVoltronPageCreate,
  PostVoltronPageDelete,
  GetVoltronPageDetail,
  PostVoltronPageList,
  PostVoltronPageUpdate,
  PostVoltronPageVersionList,
  PostVoltronProjectCreate,
  PostVoltronProjectDelete,
  GetVoltronProjectDetail,
  PostVoltronProjectList,
  PostVoltronProjectUpdate,
  PostVoltronTemplateCreate,
  PostVoltronTemplateDelete,
  GetVoltronTemplateDetail,
  PostVoltronTemplateList,
  PostVoltronTemplateUpdate,
  GetVoltronUserCurrentUser,
} from './services.types';

const omit = <T extends Record<string, any>, K extends keyof T>(
  obj: T,
  fields: K[],
): Omit<T, K> => {
  const shallowCopy = Object.assign({}, obj) as T;
  for (let i = 0; i < fields.length; i += 1) {
    const key = fields[i];
    delete shallowCopy[key as keyof T];
  }
  return shallowCopy;
};

/**
 * 接口名称：/metrics
 *
 * @description 接口路径：/metrics
 * @description 接口分组：default
 * @author openapi
 * @time 创建时间：2025-04-01 11:41:40
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getMetrics = (config: RequestConfig = {}) =>
  axios.get<GetMetrics.Res>('/metrics', {
    ...config,
  });

/**
 * 接口名称：新增评论
 *
 * @description 接口路径：/voltron/comment/create
 * @description 接口分组：评论模块 comment
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronCommentCreate = (
  params: PostVoltronCommentCreate.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronCommentCreate.Res>(
    '/voltron/comment/create',
    params,
    config,
  );

/**
 * 接口名称：删除评论
 *
 * @description 接口路径：/voltron/comment/delete
 * @description 接口分组：评论模块 comment
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronCommentDelete = (
  params: PostVoltronCommentDelete.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronCommentDelete.Res>(
    '/voltron/comment/delete',
    params,
    config,
  );

/**
 * 接口名称：获取评论详情
 *
 * @description 接口路径：/voltron/comment/detail
 * @description 接口分组：评论模块 comment
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronCommentDetail = (
  params: GetVoltronCommentDetail.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronCommentDetail.Res>('/voltron/comment/detail', {
    params,
    ...config,
  });

/**
 * 接口名称：获取评论列表
 *
 * @description 接口路径：/voltron/comment/list
 * @description 接口分组：评论模块 comment
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronCommentList = (
  params: PostVoltronCommentList.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronCommentList.Res>(
    '/voltron/comment/list',
    params,
    config,
  );

/**
 * 接口名称：编辑评论
 *
 * @description 接口路径：/voltron/comment/update
 * @description 接口分组：评论模块 comment
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronCommentUpdate = (
  params: PostVoltronCommentUpdate.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronCommentUpdate.Res>(
    '/voltron/comment/update',
    params,
    config,
  );

/**
 * 接口名称：获取完整部门树
 *
 * @description 接口路径：/voltron/common/dept/tree
 * @description 接口分组：通用模块 common
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronCommonDeptTree = (
  params: GetVoltronCommonDeptTree.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronCommonDeptTree.Res>('/voltron/common/dept/tree', {
    params,
    ...config,
  });

/**
 * 接口名称：获取码值
 *
 * @description 接口路径：/voltron/common/dict
 * @description 接口分组：通用模块 common
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronCommonDict = (config: RequestConfig = {}) =>
  axios.get<GetVoltronCommonDict.Res>('/voltron/common/dict', {
    ...config,
  });

/**
 * 接口名称：根据昵称或者域账号查询用户信息
 *
 * @description 接口路径：/voltron/common/employee/keyword
 * @description 接口分组：通用模块 common
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronCommonEmployeeKeyword = (
  params: PostVoltronCommonEmployeeKeyword.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronCommonEmployeeKeyword.Res>(
    '/voltron/common/employee/keyword',
    params,
    config,
  );

/**
 * 接口名称：接口转发
 *
 * @description 接口路径：/voltron/common/proxy
 * @description 接口分组：通用模块 common
 * @author openapi
 * @time 创建时间：2024-12-02 16:15:56
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronCommonProxy = (
  params: PostVoltronCommonProxy.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronCommonProxy.Res>(
    '/voltron/common/proxy',
    params,
    config,
  );

/**
 * 接口名称：接口转发
 *
 * @description 接口路径：/voltron/common/proxy-multi
 * @description 接口分组：通用模块 common
 * @author openapi
 * @time 创建时间：2024-12-02 16:15:56
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronCommonProxyMulti = (
  params: PostVoltronCommonProxyMulti.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronCommonProxyMulti.Res>(
    '/voltron/common/proxy-multi',
    params,
    config,
  );

/**
 * 接口名称：登录人信息
 *
 * @description 接口路径：/voltron/common/userInfo
 * @description 接口分组：通用模块 common
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronCommonUserInfo = (config: RequestConfig = {}) =>
  axios.get<GetVoltronCommonUserInfo.Res>('/voltron/common/userInfo', {
    ...config,
  });

/**
 * 接口名称：/voltron/developer/analyze-repositories
 *
 * @description 接口路径：/voltron/developer/analyze-repositories
 * @description 接口分组：开发者模块 developer
 * @author openapi
 * @time 创建时间：2025-05-13 20:58:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronDeveloperAnalyzeRepositories = (
  params: GetVoltronDeveloperAnalyzeRepositories.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronDeveloperAnalyzeRepositories.Res>(
    '/voltron/developer/analyze-repositories',
    {
      params,
      ...config,
    },
  );

/**
 * 接口名称：/voltron/developer/repositories-branches
 *
 * @description 接口路径：/voltron/developer/repositories-branches
 * @description 接口分组：开发者模块 developer
 * @author openapi
 * @time 创建时间：2025-05-13 20:58:49
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronDeveloperRepositoriesBranches = (
  params: GetVoltronDeveloperRepositoriesBranches.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronDeveloperRepositoriesBranches.Res>(
    '/voltron/developer/repositories-branches',
    {
      params,
      ...config,
    },
  );

/**
 * 接口名称：/voltron/developer/repositories-tree
 *
 * @description 接口路径：/voltron/developer/repositories-tree
 * @description 接口分组：开发者模块 developer
 * @author openapi
 * @time 创建时间：2025-05-13 20:58:49
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronDeveloperRepositoriesTree = (
  params: GetVoltronDeveloperRepositoriesTree.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronDeveloperRepositoriesTree.Res>(
    '/voltron/developer/repositories-tree',
    {
      params,
      ...config,
    },
  );

/**
 * 接口名称：/voltron/developer/schemas/component
 *
 * @description 接口路径：/voltron/developer/schemas/component
 * @description 接口分组：开发者模块 developer
 * @author openapi
 * @time 创建时间：2025-05-13 20:58:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronDeveloperSchemasComponent = (
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronDeveloperSchemasComponent.Res>(
    '/voltron/developer/schemas/component',
    {
      ...config,
    },
  );

/**
 * 接口名称：分页查询物料组件
 *
 * @description 接口路径：/voltron/material
 * @description 接口分组：物料组件
 * @author openapi
 * @time 创建时间：2025-05-17 15:58:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronMaterial = (
  params: GetVoltronMaterial.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronMaterial.Res>('/voltron/material', {
    params,
    ...config,
  });

/**
 * 接口名称：创建物料组件
 *
 * @description 接口路径：/voltron/material
 * @description 接口分组：物料组件
 * @author openapi
 * @time 创建时间：2025-05-17 15:58:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronMaterial = (
  params: PostVoltronMaterial.Req,
  config: RequestConfig = {},
) => axios.post<PostVoltronMaterial.Res>('/voltron/material', params, config);

/**
 * 接口名称：获取所有物料组件属性
 *
 * @description 接口路径：/voltron/material-prop
 * @description 接口分组：物料组件属性
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:57
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronMaterialProp = (config: RequestConfig = {}) =>
  axios.get<GetVoltronMaterialProp.Res>('/voltron/material-prop', {
    ...config,
  });

/**
 * 接口名称：创建物料组件属性
 *
 * @description 接口路径：/voltron/material-prop
 * @description 接口分组：物料组件属性
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:57
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronMaterialProp = (
  params: PostVoltronMaterialProp.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronMaterialProp.Res>(
    '/voltron/material-prop',
    params,
    config,
  );

/**
 * 接口名称：删除物料组件属性
 *
 * @description 接口路径：/voltron/material-prop/{id}
 * @description 接口分组：物料组件属性
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:58
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const deleteVoltronMaterialPropById = (
  params: DeleteVoltronMaterialPropById.Req,
  config: RequestConfig = {},
) =>
  axios.delete<DeleteVoltronMaterialPropById.Res>(
    `/voltron/material-prop/${params.id}`,
    {
      ...config,
    },
  );

/**
 * 接口名称：根据ID获取物料组件属性
 *
 * @description 接口路径：/voltron/material-prop/{id}
 * @description 接口分组：物料组件属性
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:58
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronMaterialPropById = (
  params: GetVoltronMaterialPropById.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronMaterialPropById.Res>(
    `/voltron/material-prop/${params.id}`,
    {
      ...config,
    },
  );

/**
 * 接口名称：更新物料组件属性
 *
 * @description 接口路径：/voltron/material-prop/{id}
 * @description 接口分组：物料组件属性
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:58
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const patchVoltronMaterialPropById = (
  params: PatchVoltronMaterialPropById.Req,
  config: RequestConfig = {},
) =>
  axios.patch<PatchVoltronMaterialPropById.Res>(
    `/voltron/material-prop/${params.id}`,
    omit(params, ['id']),
    config,
  );

/**
 * 接口名称：批量删除物料组件属性
 *
 * @description 接口路径：/voltron/material-prop/batch-delete
 * @description 接口分组：物料组件属性
 * @author openapi
 * @time 创建时间：2025-05-29 15:11:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.01
 */
export const postVoltronMaterialPropBatchDelete = (
  params: PostVoltronMaterialPropBatchDelete.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronMaterialPropBatchDelete.Res>(
    '/voltron/material-prop/batch-delete',
    params,
    config,
  );

/**
 * 接口名称：获取物料组件的所有属性
 *
 * @description 接口路径：/voltron/material-prop/material/{materialId}
 * @description 接口分组：物料组件属性
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:58
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronMaterialPropMaterialByMaterialId = (
  params: GetVoltronMaterialPropMaterialByMaterialId.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronMaterialPropMaterialByMaterialId.Res>(
    `/voltron/material-prop/material/${params.materialId}`,
    {
      ...config,
    },
  );

/**
 * 接口名称：删除物料组件
 *
 * @description 接口路径：/voltron/material/{id}
 * @description 接口分组：物料组件
 * @author openapi
 * @time 创建时间：2025-05-17 15:58:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const deleteVoltronMaterialById = (
  params: DeleteVoltronMaterialById.Req,
  config: RequestConfig = {},
) =>
  axios.delete<DeleteVoltronMaterialById.Res>(
    `/voltron/material/${params.id}`,
    {
      ...config,
    },
  );

/**
 * 接口名称：根据ID获取物料组件
 *
 * @description 接口路径：/voltron/material/{id}
 * @description 接口分组：物料组件
 * @author openapi
 * @time 创建时间：2025-05-17 15:58:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronMaterialById = (
  params: GetVoltronMaterialById.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronMaterialById.Res>(`/voltron/material/${params.id}`, {
    ...config,
  });

/**
 * 接口名称：更新物料组件
 *
 * @description 接口路径：/voltron/material/{id}
 * @description 接口分组：物料组件
 * @author openapi
 * @time 创建时间：2025-05-17 15:58:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const patchVoltronMaterialById = (
  params: PatchVoltronMaterialById.Req,
  config: RequestConfig = {},
) =>
  axios.patch<PatchVoltronMaterialById.Res>(
    `/voltron/material/${params.id}`,
    omit(params, ['id']),
    config,
  );

/**
 * 接口名称：删除物料组件及其属性
 *
 * @description 接口路径：/voltron/material/{id}/full
 * @description 接口分组：物料组件
 * @author openapi
 * @time 创建时间：2025-05-21 07:56:29
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const deleteVoltronMaterialFullById = (
  params: DeleteVoltronMaterialFullById.Req,
  config: RequestConfig = {},
) =>
  axios.delete<DeleteVoltronMaterialFullById.Res>(
    `/voltron/material/${params.id}/full`,
    {
      ...config,
    },
  );

/**
 * 接口名称：获取物料组件详情（包含属性）
 *
 * @description 接口路径：/voltron/material/{id}/full
 * @description 接口分组：物料组件
 * @author openapi
 * @time 创建时间：2025-05-21 07:56:29
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronMaterialFullById = (
  params: GetVoltronMaterialFullById.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronMaterialFullById.Res>(
    `/voltron/material/${params.id}/full`,
    {
      ...config,
    },
  );

/**
 * 接口名称：根据包名删除物料组件及其属性
 *
 * @description 接口路径：/voltron/material/package
 * @description 接口分组：物料组件
 * @author openapi
 * @time 创建时间：2025-05-21 07:56:29
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const deleteVoltronMaterialPackage = (
  params: DeleteVoltronMaterialPackage.Req,
  config: RequestConfig = {},
) =>
  axios.delete<DeleteVoltronMaterialPackage.Res>('/voltron/material/package', {
    params,
    ...config,
  });

/**
 * 接口名称：根据包名查询物料组件及其属性
 *
 * @description 接口路径：/voltron/material/package
 * @description 接口分组：物料组件
 * @author openapi
 * @time 创建时间：2025-05-21 07:58:05
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronMaterialPackage = (
  params: GetVoltronMaterialPackage.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronMaterialPackage.Res>('/voltron/material/package', {
    params,
    ...config,
  });

/**
 * 接口名称：获取所有物料组件包名
 *
 * @description 接口路径：/voltron/material/packages
 * @description 接口分组：物料组件
 * @author openapi
 * @time 创建时间：2025-05-17 15:58:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronMaterialPackages = (config: RequestConfig = {}) =>
  axios.get<GetVoltronMaterialPackages.Res>('/voltron/material/packages', {
    ...config,
  });

/**
 * 接口名称：批量更新物料组件属性
 *
 * @description 接口路径：/voltron/material/props/batch
 * @description 接口分组：物料组件
 * @author openapi
 * @time 创建时间：2025-05-21 07:56:29
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const patchVoltronMaterialPropsBatch = (
  params: PatchVoltronMaterialPropsBatch.Req,
  config: RequestConfig = {},
) =>
  axios.patch<PatchVoltronMaterialPropsBatch.Res>(
    '/voltron/material/props/batch',
    params,
    config,
  );

/**
 * 接口名称：创建模块
 *
 * @description 接口路径：/voltron/module/create
 * @description 接口分组：模块 module
 * @author openapi
 * @time 创建时间：2025-03-24 16:57:26
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronModuleCreate = (
  params: PostVoltronModuleCreate.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronModuleCreate.Res>(
    '/voltron/module/create',
    params,
    config,
  );

/**
 * 接口名称：删除模块
 *
 * @description 接口路径：/voltron/module/delete
 * @description 接口分组：模块 module
 * @author openapi
 * @time 创建时间：2025-03-24 16:57:26
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronModuleDelete = (
  params: PostVoltronModuleDelete.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronModuleDelete.Res>(
    '/voltron/module/delete',
    params,
    config,
  );

/**
 * 接口名称：获取模块列表
 *
 * @description 接口路径：/voltron/module/list
 * @description 接口分组：模块 module
 * @author openapi
 * @time 创建时间：2025-03-24 16:57:26
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronModuleList = (
  params: GetVoltronModuleList.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronModuleList.Res>('/voltron/module/list', {
    params,
    ...config,
  });

/**
 * 接口名称：获取所有模块列表
 *
 * @description 接口路径：/voltron/module/list-all
 * @description 接口分组：模块 module
 * @author openapi
 * @time 创建时间：2025-03-24 17:40:30
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronModuleListAll = (
  params: GetVoltronModuleListAll.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronModuleListAll.Res>('/voltron/module/list-all', {
    params,
    ...config,
  });

/**
 * 接口名称：更新模块
 *
 * @description 接口路径：/voltron/module/update
 * @description 接口分组：模块 module
 * @author openapi
 * @time 创建时间：2025-03-24 16:57:26
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronModuleUpdate = (
  params: PostVoltronModuleUpdate.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronModuleUpdate.Res>(
    '/voltron/module/update',
    params,
    config,
  );

/**
 * 接口名称：获取顶部导航列表
 *
 * @description 接口路径：/voltron/navigation/list
 * @description 接口分组：顶部导航模块 navigation
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronNavigationList = (
  params: GetVoltronNavigationList.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronNavigationList.Res>('/voltron/navigation/list', {
    params,
    ...config,
  });

/**
 * 接口名称：更新顶部导航
 *
 * @description 接口路径：/voltron/navigation/update
 * @description 接口分组：顶部导航模块 navigation
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronNavigationUpdate = (
  params: PostVoltronNavigationUpdate.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronNavigationUpdate.Res>(
    '/voltron/navigation/update',
    params,
    config,
  );

/**
 * 接口名称：创建批注
 *
 * @description 接口路径：/voltron/note/create
 * @description 接口分组：批注模块 note
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronNoteCreate = (
  params: PostVoltronNoteCreate.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronNoteCreate.Res>('/voltron/note/create', params, config);

/**
 * 接口名称：删除批注
 *
 * @description 接口路径：/voltron/note/delete
 * @description 接口分组：批注模块 note
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronNoteDelete = (
  params: PostVoltronNoteDelete.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronNoteDelete.Res>('/voltron/note/delete', params, config);

/**
 * 接口名称：获取批注列表
 *
 * @description 接口路径：/voltron/note/list
 * @description 接口分组：批注模块 note
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronNoteList = (
  params: GetVoltronNoteList.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronNoteList.Res>('/voltron/note/list', {
    params,
    ...config,
  });

/**
 * 接口名称：更新批注
 *
 * @description 接口路径：/voltron/note/update
 * @description 接口分组：批注模块 note
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronNoteUpdate = (
  params: PostVoltronNoteUpdate.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronNoteUpdate.Res>('/voltron/note/update', params, config);

/**
 * 接口名称：创建页面
 *
 * @description 接口路径：/voltron/page/create
 * @description 接口分组：页面模块 page
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronPageCreate = (
  params: PostVoltronPageCreate.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronPageCreate.Res>('/voltron/page/create', params, config);

/**
 * 接口名称：删除页面
 *
 * @description 接口路径：/voltron/page/delete
 * @description 接口分组：页面模块 page
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 20:31:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronPageDelete = (
  params: PostVoltronPageDelete.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronPageDelete.Res>('/voltron/page/delete', params, config);

/**
 * 接口名称：获取页面详情
 *
 * @description 接口路径：/voltron/page/detail
 * @description 接口分组：页面模块 page
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronPageDetail = (
  params: GetVoltronPageDetail.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronPageDetail.Res>('/voltron/page/detail', {
    params,
    ...config,
  });

/**
 * 接口名称：获取页面列表
 *
 * @description 接口路径：/voltron/page/list
 * @description 接口分组：页面模块 page
 * @author openapi
 * @time 创建时间：2024-11-21 20:31:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronPageList = (
  params: PostVoltronPageList.Req,
  config: RequestConfig = {},
) => axios.post<PostVoltronPageList.Res>('/voltron/page/list', params, config);

/**
 * 接口名称：更新页面
 *
 * @description 接口路径：/voltron/page/update
 * @description 接口分组：页面模块 page
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronPageUpdate = (
  params: PostVoltronPageUpdate.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronPageUpdate.Res>('/voltron/page/update', params, config);

/**
 * 接口名称：获取页面版本列表
 *
 * @description 接口路径：/voltron/page/version/list
 * @description 接口分组：页面模块 page
 * @author openapi
 * @time 创建时间：2024-11-26 15:09:56
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronPageVersionList = (
  params: PostVoltronPageVersionList.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronPageVersionList.Res>(
    '/voltron/page/version/list',
    params,
    config,
  );

/**
 * 接口名称：创建项目
 *
 * @description 接口路径：/voltron/project/create
 * @description 接口分组：项目模块 project
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronProjectCreate = (
  params: PostVoltronProjectCreate.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronProjectCreate.Res>(
    '/voltron/project/create',
    params,
    config,
  );

/**
 * 接口名称：删除项目
 *
 * @description 接口路径：/voltron/project/delete
 * @description 接口分组：项目模块 project
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronProjectDelete = (
  params: PostVoltronProjectDelete.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronProjectDelete.Res>(
    '/voltron/project/delete',
    params,
    config,
  );

/**
 * 接口名称：获取项目详情
 *
 * @description 接口路径：/voltron/project/detail
 * @description 接口分组：项目模块 project
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronProjectDetail = (
  params: GetVoltronProjectDetail.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronProjectDetail.Res>('/voltron/project/detail', {
    params,
    ...config,
  });

/**
 * 接口名称：获取项目列表
 *
 * @description 接口路径：/voltron/project/list
 * @description 接口分组：项目模块 project
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronProjectList = (
  params: PostVoltronProjectList.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronProjectList.Res>(
    '/voltron/project/list',
    params,
    config,
  );

/**
 * 接口名称：编辑项目
 *
 * @description 接口路径：/voltron/project/update
 * @description 接口分组：项目模块 project
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronProjectUpdate = (
  params: PostVoltronProjectUpdate.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronProjectUpdate.Res>(
    '/voltron/project/update',
    params,
    config,
  );

/**
 * 接口名称：创建模板
 *
 * @description 接口路径：/voltron/template/create
 * @description 接口分组：模板模块 template
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronTemplateCreate = (
  params: { coverUrl: string; name: string; projectId: string; templateUrl: string },
  config: RequestConfig = {}
) =>
  axios.post<PostVoltronTemplateCreate.Res>(
    '/voltron/template/create',
    params,
    config,
  );

/**
 * 接口名称：删除模板
 *
 * @description 接口路径：/voltron/template/delete
 * @description 接口分组：模板模块 template
 * @author openapi
 * @time 创建时间：2024-11-21 20:31:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronTemplateDelete = (
  params: PostVoltronTemplateDelete.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronTemplateDelete.Res>(
    '/voltron/template/delete',
    params,
    config,
  );

/**
 * 接口名称：获取模板详情
 *
 * @description 接口路径：/voltron/template/detail
 * @description 接口分组：模板模块 template
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronTemplateDetail = (
  params: GetVoltronTemplateDetail.Req,
  config: RequestConfig = {},
) =>
  axios.get<GetVoltronTemplateDetail.Res>('/voltron/template/detail', {
    params,
    ...config,
  });

/**
 * 接口名称：获取模板列表
 *
 * @description 接口路径：/voltron/template/list
 * @description 接口分组：模板模块 template
 * @author openapi
 * @time 创建时间：2024-11-21 20:31:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronTemplateList = (
  params: PostVoltronTemplateList.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronTemplateList.Res>(
    '/voltron/template/list',
    params,
    config,
  );

/**
 * 接口名称：编辑模板
 *
 * @description 接口路径：/voltron/template/update
 * @description 接口分组：模板模块 template
 * @author openapi
 * @time 创建时间：2024-11-21 20:31:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const postVoltronTemplateUpdate = (
  params: PostVoltronTemplateUpdate.Req,
  config: RequestConfig = {},
) =>
  axios.post<PostVoltronTemplateUpdate.Res>(
    '/voltron/template/update',
    params,
    config,
  );

/**
 * 接口名称：获取当前用户信息
 *
 * @description 接口路径：/voltron/user/current-user
 * @description 接口分组：用户
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:58
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export const getVoltronUserCurrentUser = (config: RequestConfig = {}) =>
  axios.get<GetVoltronUserCurrentUser.Res>('/voltron/user/current-user', {
    ...config,
  });
