/* eslint-disable */
/**
 * This file was automatically generated by bee-bapi-to-ts.
 * DO NOT MODIFY IT BY HAND.
 */

/**
 * 类型名称：/metrics
 *
 * @description 接口路径：/metrics
 * @description 接口分组：default
 * @author openapi
 * @time 创建时间：2025-04-01 11:41:40
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetMetrics {
  export type Res = any;
}

/**
 * 类型名称：新增评论
 *
 * @description 接口路径：/voltron/comment/create
 * @description 接口分组：评论模块 comment
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronCommentCreate {
  export interface Req {
    /**
     * 组件ID
     */
    componentId: string;
    /**
     * 评论内容
     */
    content: string;
    /**
     * 页面ID
     */
    pageId: string;
    /**
     * 左边坐标
     */
    positionLeft: number;
    /**
     * 顶部坐标
     */
    positionTop: number;
  }
  export interface Res {
    /**
     * 评论ID
     */
    commentId?: string;
    /**
     * 组件ID
     */
    componentId?: string;
    /**
     * 评论内容
     */
    content?: string;
    /**
     * 评论创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 是否作者评论
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 页面ID
     */
    pageId?: string;
    /**
     * left坐标
     */
    positionLeft?: number;
    /**
     * top坐标
     */
    positionTop?: number;
    /**
     * 是否解决
     */
    resolved?: number;
    /**
     * 评论更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：删除评论
 *
 * @description 接口路径：/voltron/comment/delete
 * @description 接口分组：评论模块 comment
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronCommentDelete {
  export type Res = any;

  export interface Req {
    /**
     * 评论ID
     */
    commentId: string;
  }
}

/**
 * 类型名称：获取评论详情
 *
 * @description 接口路径：/voltron/comment/detail
 * @description 接口分组：评论模块 comment
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronCommentDetail {
  export interface Req {
    commentId: string;
  }
  export interface Res {
    /**
     * 评论ID
     */
    commentId?: string;
    /**
     * 组件ID
     */
    componentId?: string;
    /**
     * 评论内容
     */
    content?: string;
    /**
     * 评论创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 是否作者评论
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 页面ID
     */
    pageId?: string;
    /**
     * left坐标
     */
    positionLeft?: number;
    /**
     * top坐标
     */
    positionTop?: number;
    /**
     * 是否解决
     */
    resolved?: number;
    /**
     * 评论更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：获取评论列表
 *
 * @description 接口路径：/voltron/comment/list
 * @description 接口分组：评论模块 comment
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronCommentList {
  /**
   * res
   */
  export type Res = ResItem[];

  export interface Req {
    /**
     * 页面ID
     */
    pageId: string;
  }
  export interface ResItem {
    /**
     * 评论ID
     */
    commentId?: string;
    /**
     * 组件ID
     */
    componentId?: string;
    /**
     * 评论内容
     */
    content?: string;
    /**
     * 评论创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 是否作者评论
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 页面ID
     */
    pageId?: string;
    /**
     * left坐标
     */
    positionLeft?: number;
    /**
     * top坐标
     */
    positionTop?: number;
    /**
     * 是否解决
     */
    resolved?: number;
    /**
     * 评论更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：编辑评论
 *
 * @description 接口路径：/voltron/comment/update
 * @description 接口分组：评论模块 comment
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronCommentUpdate {
  export interface Req {
    /**
     * 评论ID
     */
    commentId: string;
    /**
     * 评论内容
     */
    content?: string;
    /**
     * 左边坐标
     */
    positionLeft?: number;
    /**
     * 顶部坐标
     */
    positionTop?: number;
    /**
     * 是否解决
     */
    resolved?: boolean;
  }
  export interface Res {
    /**
     * 评论ID
     */
    commentId?: string;
    /**
     * 组件ID
     */
    componentId?: string;
    /**
     * 评论内容
     */
    content?: string;
    /**
     * 评论创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 是否作者评论
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 页面ID
     */
    pageId?: string;
    /**
     * left坐标
     */
    positionLeft?: number;
    /**
     * top坐标
     */
    positionTop?: number;
    /**
     * 是否解决
     */
    resolved?: number;
    /**
     * 评论更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：获取完整部门树
 *
 * @description 接口路径：/voltron/common/dept/tree
 * @description 接口分组：通用模块 common
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronCommonDeptTree {
  export type Res = any;

  export interface Req {
    deptCode: string;
  }
}

/**
 * 类型名称：获取码值
 *
 * @description 接口路径：/voltron/common/dict
 * @description 接口分组：通用模块 common
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronCommonDict {
  export interface Res {
    searchTypeDict?: SearchTypeDictItem[];
    tagList?: string[];
  }
  export interface SearchTypeDictItem {
    label: string;
    value: string;
  }
}

/**
 * 类型名称：根据昵称或者域账号查询用户信息
 *
 * @description 接口路径：/voltron/common/employee/keyword
 * @description 接口分组：通用模块 common
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronCommonEmployeeKeyword {
  export interface Req {
    keyword: string;
    /**
     * 页码
     */
    pageNum: number;
    /**
     * 页数
     * @enum 2,5,10,20,30,40,50,60,70,80,100
     */
    pageSize: number;
  }
  export interface Res {
    /**
     * 人员列表
     */
    list?: ListItem[];
    pageNum?: number;
    pageSize?: number;
    pages?: number;
    total?: number;
  }
  export interface ListItem {
    adAccount?: string;
    avatarUrl?: string;
    deptCode?: string;
    deptCodeSeq?: string;
    deptName?: string;
    deptNameSeq?: string;
    nickName?: string;
  }
}

/**
 * 类型名称：接口转发
 *
 * @description 接口路径：/voltron/common/proxy
 * @description 接口分组：通用模块 common
 * 
 * @author openapi
 * @time 创建时间：2024-12-02 16:15:56
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronCommonProxy {
  export type Res = any;

  export interface Req {
    /**
     * baseURL
     */
    baseURL?: string;
    /**
     * data参数
     */
    data?: any;
    /**
     * header信息
     */
    headers?: any;
    /**
     * 接口类型
     * @default GET
     */
    method?: string;
    /**
     * params参数
     */
    params?: any;
    /**
     * timeout
     */
    timeout?: number;
    /**
     * 接口路径
     */
    url: string;
  }
}

/**
 * 类型名称：接口转发
 *
 * @description 接口路径：/voltron/common/proxy-multi
 * @description 接口分组：通用模块 common
 * 
 * @author openapi
 * @time 创建时间：2024-12-02 16:15:56
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronCommonProxyMulti {
  export type Res = any;

  export interface Req {
    list: ListItem[];
  }
  export interface ListItem {
    /**
     * baseURL
     */
    baseURL?: string;
    /**
     * data参数
     */
    data?: any;
    /**
     * header信息
     */
    headers?: any;
    /**
     * 接口类型
     * @default GET
     */
    method?: string;
    /**
     * params参数
     */
    params?: any;
    /**
     * timeout
     */
    timeout?: number;
    /**
     * 接口路径
     */
    url: string;
  }
}

/**
 * 类型名称：登录人信息
 *
 * @description 接口路径：/voltron/common/userInfo
 * @description 接口分组：通用模块 common
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronCommonUserInfo {
  export interface Res {
    adAccount?: string;
    avatarUrl?: string;
    deptCode?: string;
    deptCodeSeq?: string;
    deptName?: string;
    deptNameSeq?: string;
    nickName?: string;
  }
}

/**
 * 类型名称：/voltron/developer/analyze-repositories
 *
 * @description 接口路径：/voltron/developer/analyze-repositories
 * @description 接口分组：开发者模块 developer
 * 
 * @author openapi
 * @time 创建时间：2025-05-13 20:58:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronDeveloperAnalyzeRepositories {
  export type Res = any;

  export interface Req {
    componentsPath: string;
    ref: string;
    repository: string;
  }
}

/**
 * 类型名称：/voltron/developer/repositories-branches
 *
 * @description 接口路径：/voltron/developer/repositories-branches
 * @description 接口分组：开发者模块 developer
 * 
 * @author openapi
 * @time 创建时间：2025-05-13 20:58:49
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronDeveloperRepositoriesBranches {
  export type Res = any;

  export interface Req {
    repo: string;
    search: string;
  }
}

/**
 * 类型名称：/voltron/developer/repositories-tree
 *
 * @description 接口路径：/voltron/developer/repositories-tree
 * @description 接口分组：开发者模块 developer
 * 
 * @author openapi
 * @time 创建时间：2025-05-13 20:58:49
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronDeveloperRepositoriesTree {
  export type Res = any;

  export interface Req {
    path: string;
    ref: string;
    repo: string;
  }
}

/**
 * 类型名称：/voltron/developer/schemas/component
 *
 * @description 接口路径：/voltron/developer/schemas/component
 * @description 接口分组：开发者模块 developer
 * 
 * @author openapi
 * @time 创建时间：2025-05-13 20:58:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronDeveloperSchemasComponent {
  export type Res = any;
}

/**
 * 类型名称：分页查询物料组件
 *
 * @description 接口路径：/voltron/material
 * @description 接口分组：物料组件
 * 
 * @author openapi
 * @time 创建时间：2025-05-17 15:58:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronMaterial {
  export type Res = any;

  export interface Req {
    _t?: number;
    /**
     * 物料组件中文名称
     */
    displayName?: string;
    /**
     * 物料组件导入名
     */
    importName?: string;
    order?: string;
    orderField?: string;
    pageNum: number;
    pageSize: number;
  }
}

/**
 * 类型名称：创建物料组件
 *
 * @description 接口路径：/voltron/material
 * @description 接口分组：物料组件
 * 
 * @author openapi
 * @time 创建时间：2025-05-17 15:58:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronMaterial {
  export type Res = any;

  export interface Req {
    /**
     * 物料组件调用名
     */
    callingName: string;
    /**
     * 物料组件类别
     */
    categories: string;
    /**
     * 所属物料组件库包名
     */
    configName: string;
    /**
     * 物料组件封面
     */
    coverUrl: string;
    /**
     * 物料组件中文名称
     */
    displayName: string;
    /**
     * 物料组件特性
     */
    feature?: string;
    /**
     * 物料组件导入名
     */
    importName: string;
    /**
     * 是否为黑盒组件
     */
    // isBlackBox?: number;
    /**
     * 是否为一个隐藏组件
     */
    isHidden?: number;
    /**
     * 是否为图层组件
     */
    isLayer?: number;
    /**
     * 物料组件搜索关键字
     */
    keywords: string;
    /**
     * 是否不需要生成导入语句
     */
    needImport?: number;
    /**
     * 所属物料组件库包名
     */
    package: string;
    /**
     * 物料组件属性列表
     */
    props?: PropsItem[];
  }
  export interface PropsItem {
    /**
     * 类别
     */
    category: string;
    /**
     * 默认值
     */
    defaultValue?: string;
    /**
     * 属性名称
     */
    displayName?: string;
    /**
     * 是否显示该字段
     */
    isVisible?: number;
    /**
     * 属性英文名称
     */
    propName: string;
    /**
     * 初始值
     */
    propValue?: string;
    /**
     * 模板属性路径
     */
    templateKeyPathsReg?: string;
    /**
     * 值来源
     */
    valueSource: string;
    /**
     * 数据类型
     */
    valueType: string;
  }
}

/**
 * 类型名称：获取所有物料组件属性
 *
 * @description 接口路径：/voltron/material-prop
 * @description 接口分组：物料组件属性
 * 
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:57
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronMaterialProp {
  /**
   * res
   */
  export type Res = ResItem[];

  export interface ResItem {
    /**
     * 类别
     */
    category: string;
    ctime: string;
    /**
     * 默认值
     */
    defaultValue: string;
    /**
     * 属性名称
     */
    displayName: string;
    id: number;
    /**
     * 是否显示该字段
     */
    isVisible: number;
    material: any;
    mtime: string;
    /**
     * 属性英文名称
     */
    propName: string;
    /**
     * 初始值
     */
    propValue: string;
    /**
     * 模板属性路径
     */
    templateKeyPathsReg: string;
    /**
     * 值来源
     */
    valueSource: string;
    /**
     * 数据类型
     */
    valueType: string;
    /**
     * 属性所属的物料组件ID
     */
    voltronMaterialId: number;
  }
}

/**
 * 类型名称：创建物料组件属性
 *
 * @description 接口路径：/voltron/material-prop
 * @description 接口分组：物料组件属性
 * 
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:57
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronMaterialProp {
  export interface Req {
    /**
     * 类别
     */
    category: string;
    /**
     * 默认值
     */
    defaultValue?: string;
    /**
     * 属性名称
     */
    displayName?: string;
    /**
     * 是否显示该字段
     */
    isVisible?: number;
    /**
     * 属性英文名称
     */
    propName: string;
    /**
     * 初始值
     */
    propValue?: string;
    /**
     * 模板属性路径
     */
    templateKeyPathsReg?: string;
    /**
     * 值来源
     */
    valueSource: string;
    /**
     * 数据类型
     */
    valueType: string;
  }
  export interface Res {
    /**
     * 类别
     */
    category: string;
    ctime: string;
    /**
     * 默认值
     */
    defaultValue: string;
    /**
     * 属性名称
     */
    displayName: string;
    id: number;
    /**
     * 是否显示该字段
     */
    isVisible: number;
    material: any;
    mtime: string;
    /**
     * 属性英文名称
     */
    propName: string;
    /**
     * 初始值
     */
    propValue: string;
    /**
     * 模板属性路径
     */
    templateKeyPathsReg: string;
    /**
     * 值来源
     */
    valueSource: string;
    /**
     * 数据类型
     */
    valueType: string;
    /**
     * 属性所属的物料组件ID
     */
    voltronMaterialId: number;
  }
}

/**
 * 类型名称：删除物料组件属性
 *
 * @description 接口路径：/voltron/material-prop/{id}
 * @description 接口分组：物料组件属性
 * 
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:58
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace DeleteVoltronMaterialPropById {
  export type Res = any;

  export interface Req {
    id: string;
  }
}

/**
 * 类型名称：根据ID获取物料组件属性
 *
 * @description 接口路径：/voltron/material-prop/{id}
 * @description 接口分组：物料组件属性
 * 
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:58
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronMaterialPropById {
  export type Res = any;

  export interface Req {
    id: string;
  }
}

/**
 * 类型名称：更新物料组件属性
 *
 * @description 接口路径：/voltron/material-prop/{id}
 * @description 接口分组：物料组件属性
 * 
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:58
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PatchVoltronMaterialPropById {
  export type Res = any;

  export interface Req {
    /**
     * 类别
     */
    category?: string;
    /**
     * 默认值
     */
    defaultValue?: string;
    /**
     * 属性名称
     */
    displayName?: string;
    /**
     * 属性ID
     */
    id: number;
    /**
     * 是否显示该字段
     */
    isVisible?: number;
    /**
     * 属性英文名称
     */
    propName?: string;
    /**
     * 初始值
     */
    propValue?: string;
    /**
     * 模板属性路径
     */
    templateKeyPathsReg?: string;
    /**
     * 值来源
     */
    valueSource?: string;
    /**
     * 数据类型
     */
    valueType?: string;
  }
}

/**
 * 类型名称：批量删除物料组件属性
 *
 * @description 接口路径：/voltron/material-prop/batch-delete
 * @description 接口分组：物料组件属性
 * 
 * @author openapi
 * @time 创建时间：2025-05-29 15:11:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.01
 */
export namespace PostVoltronMaterialPropBatchDelete {
  export type Res = any;

  export interface Req {
    /**
     * 要删除的属性ID列表
     */
    ids: number[];
  }
}

/**
 * 类型名称：获取物料组件的所有属性
 *
 * @description 接口路径：/voltron/material-prop/material/{materialId}
 * @description 接口分组：物料组件属性
 * 
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:58
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronMaterialPropMaterialByMaterialId {
  /**
   * res
   */
  export type Res = ResItem[];

  export interface Req {
    materialId: string;
  }
  export interface ResItem {
    /**
     * 类别
     */
    category: string;
    ctime: string;
    /**
     * 默认值
     */
    defaultValue: string;
    /**
     * 属性名称
     */
    displayName: string;
    id: number;
    /**
     * 是否显示该字段
     */
    isVisible: number;
    material: any;
    mtime: string;
    /**
     * 属性英文名称
     */
    propName: string;
    /**
     * 初始值
     */
    propValue: string;
    /**
     * 模板属性路径
     */
    templateKeyPathsReg: string;
    /**
     * 值来源
     */
    valueSource: string;
    /**
     * 数据类型
     */
    valueType: string;
    /**
     * 属性所属的物料组件ID
     */
    voltronMaterialId: number;
  }
}

/**
 * 类型名称：删除物料组件
 *
 * @description 接口路径：/voltron/material/{id}
 * @description 接口分组：物料组件
 * 
 * @author openapi
 * @time 创建时间：2025-05-17 15:58:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace DeleteVoltronMaterialById {
  export type Res = any;

  export interface Req {
    id: string;
  }
}

/**
 * 类型名称：根据ID获取物料组件
 *
 * @description 接口路径：/voltron/material/{id}
 * @description 接口分组：物料组件
 * 
 * @author openapi
 * @time 创建时间：2025-05-17 15:58:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronMaterialById {
  export type Res = any;

  export interface Req {
    id: string;
  }
}

/**
 * 类型名称：更新物料组件
 *
 * @description 接口路径：/voltron/material/{id}
 * @description 接口分组：物料组件
 * 
 * @author openapi
 * @time 创建时间：2025-05-17 15:58:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PatchVoltronMaterialById {
  export type Res = any;

  export interface Req {
    /**
     * 物料组件调用名
     */
    callingName?: string;
    /**
     * 物料组件类别
     */
    categories?: string;
    /**
     * 所属物料组件库包名
     */
    configName?: string;
    /**
     * 物料组件封面
     */
    coverUrl?: string;
    /**
     * 物料组件中文名称
     */
    displayName?: string;
    /**
     * 物料组件特性
     */
    feature?: string;
    id: string;
    /**
     * 物料组件导入名
     */
    importName?: string;
    /**
     * 是否为黑盒组件
     */
    // isBlackBox?: number;
    /**
     * 是否为一个隐藏组件
     */
    isHidden?: number;
    /**
     * 是否为图层组件
     */
    isLayer?: number;
    /**
     * 物料组件搜索关键字
     */
    keywords?: string;
    /**
     * 是否不需要生成导入语句
     */
    needImport?: number;
    /**
     * 所属物料组件库包名
     */
    package?: string;
    /**
     * 物料组件属性列表
     */
    props?: PropsItem[];
  }
  export interface PropsItem {
    /**
     * 类别
     */
    category: string;
    /**
     * 默认值
     */
    defaultValue?: string;
    /**
     * 属性名称
     */
    displayName?: string;
    /**
     * 是否显示该字段
     */
    isVisible?: number;
    /**
     * 属性英文名称
     */
    propName: string;
    /**
     * 初始值
     */
    propValue?: string;
    /**
     * 模板属性路径
     */
    templateKeyPathsReg?: string;
    /**
     * 值来源
     */
    valueSource: string;
    /**
     * 数据类型
     */
    valueType: string;
  }
}

/**
 * 类型名称：删除物料组件及其属性
 *
 * @description 接口路径：/voltron/material/{id}/full
 * @description 接口分组：物料组件
 * 
 * @author openapi
 * @time 创建时间：2025-05-21 07:56:29
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace DeleteVoltronMaterialFullById {
  export type Res = any;

  export interface Req {
    /**
     * 物料组件ID
     */
    id: string;
  }
}

/**
 * 类型名称：获取物料组件详情（包含属性）
 *
 * @description 接口路径：/voltron/material/{id}/full
 * @description 接口分组：物料组件
 * 
 * @author openapi
 * @time 创建时间：2025-05-21 07:56:29
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronMaterialFullById {
  export type Res = any;

  export interface Req {
    id: string;
  }
}

/**
 * 类型名称：根据包名删除物料组件及其属性
 *
 * @description 接口路径：/voltron/material/package
 * @description 接口分组：物料组件
 * 
 * @author openapi
 * @time 创建时间：2025-05-21 07:56:29
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace DeleteVoltronMaterialPackage {
  export type Res = any;

  export interface Req {
    /**
     * 物料组件包名
     */
    packageName: string;
  }
}

/**
 * 类型名称：根据包名查询物料组件及其属性
 *
 * @description 接口路径：/voltron/material/package
 * @description 接口分组：物料组件
 * 
 * @author openapi
 * @time 创建时间：2025-05-21 07:58:05
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronMaterialPackage {
  export type ResItem = any;
  /**
   * res
   */
  export type Res = ResItem[];

  export interface Req {
    /**
     * 物料组件包名
     */
    packageName: string;
  }
}

/**
 * 类型名称：获取所有物料组件包名
 *
 * @description 接口路径：/voltron/material/packages
 * @description 接口分组：物料组件
 * 
 * @author openapi
 * @time 创建时间：2025-05-17 15:58:23
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronMaterialPackages {
  export type ResItem = any;
  /**
   * res
   */
  export type Res = ResItem[];
}

/**
 * 类型名称：批量更新物料组件属性
 *
 * @description 接口路径：/voltron/material/props/batch
 * @description 接口分组：物料组件
 * 
 * @author openapi
 * @time 创建时间：2025-05-21 07:56:29
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PatchVoltronMaterialPropsBatch {
  export type Res = any;

  export interface Req {
    /**
     * 物料组件ID
     */
    materialId: number;
    /**
     * 要更新的属性列表
     */
    props: PropsItem[];
  }
  export interface PropsItem {
    /**
     * 类别
     */
    category?: string;
    /**
     * 默认值
     */
    defaultValue?: string;
    /**
     * 属性名称
     */
    displayName?: string;
    /**
     * 属性ID
     */
    id: number;
    /**
     * 是否显示该字段
     */
    isVisible?: number;
    /**
     * 属性英文名称
     */
    propName?: string;
    /**
     * 初始值
     */
    propValue?: string;
    /**
     * 模板属性路径
     */
    templateKeyPathsReg?: string;
    /**
     * 值来源
     */
    valueSource?: string;
    /**
     * 数据类型
     */
    valueType?: string;
  }
}

/**
 * 类型名称：创建模块
 *
 * @description 接口路径：/voltron/module/create
 * @description 接口分组：模块 module
 * 
 * @author openapi
 * @time 创建时间：2025-03-24 16:57:26
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronModuleCreate {
  export type Res = boolean;

  export interface Req {
    /**
     * 类别
     */
    category?: number;
    /**
     * 封面链接
     */
    coverUrl: string;
    /**
     * 模块名称
     */
    name: string;
    /**
     * 模块链接
     */
    url: string;
  }
}

/**
 * 类型名称：删除模块
 *
 * @description 接口路径：/voltron/module/delete
 * @description 接口分组：模块 module
 * 
 * @author openapi
 * @time 创建时间：2025-03-24 16:57:26
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronModuleDelete {
  export type Res = boolean;

  export interface Req {
    /**
     * 类别（0-模块，1-单组件，2-页面）
     */
    category?: number;
    /**
     * 封面链接
     */
    coverUrl?: string;
    ctime?: string;
    /**
     * 模块ID
     */
    id: number;
    /**
     * 模块ID
     */
    moduleId?: string;
    mtime?: string;
    /**
     * 组件模块名称
     */
    name?: string;
    /**
     * 模块DSL链接
     */
    url?: string;
  }
}

/**
 * 类型名称：获取模块列表
 *
 * @description 接口路径：/voltron/module/list
 * @description 接口分组：模块 module
 * 
 * @author openapi
 * @time 创建时间：2025-03-24 16:57:26
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronModuleList {
  export interface Req {
    _t?: number;
    /**
     * 模块名称
     */
    name?: string;
    order?: string;
    orderField?: string;
    pageNum: number;
    pageSize: number;
  }
  export interface Res {
    list?: ListItem[];
    pageNum?: number;
    pageSize?: number;
    pages?: number;
    size?: number;
    total?: number;
  }
  export interface ListItem {
    /**
     * 类别（0-模块，1-单组件，2-页面）
     */
    category: number;
    /**
     * 封面链接
     */
    coverUrl: string;
    ctime: string;
    id: number;
    /**
     * 模块ID
     */
    moduleId: string;
    mtime: string;
    /**
     * 组件模块名称
     */
    name: string;
    /**
     * 模块DSL链接
     */
    url: string;
  }
}

/**
 * 类型名称：获取所有模块列表
 *
 * @description 接口路径：/voltron/module/list-all
 * @description 接口分组：模块 module
 * 
 * @author openapi
 * @time 创建时间：2025-03-24 17:40:30
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronModuleListAll {
  export interface Req {
    /**
     * 模块名称
     */
    name?: string;
    order?: string;
    orderField?: string;
  }
  export interface Res {
    list?: ListItem[];
    total?: number;
  }
  export interface ListItem {
    /**
     * 类别（0-模块，1-单组件，2-页面）
     */
    category: number;
    /**
     * 封面链接
     */
    coverUrl: string;
    ctime: string;
    /**
     * dsl
     */
    dsl?: any;
    id: number;
    /**
     * 模块ID
     */
    moduleId: string;
    mtime: string;
    /**
     * 组件模块名称
     */
    name: string;
    /**
     * 模块DSL链接
     */
    url: string;
  }
}

/**
 * 类型名称：更新模块
 *
 * @description 接口路径：/voltron/module/update
 * @description 接口分组：模块 module
 * 
 * @author openapi
 * @time 创建时间：2025-03-24 16:57:26
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronModuleUpdate {
  export type Res = boolean;

  export interface Req {
    /**
     * 类别
     */
    category?: number;
    /**
     * 封面链接
     */
    coverUrl?: string;
    /**
     * 模块ID
     */
    id: number;
    /**
     * 模块名称
     */
    name?: string;
    /**
     * 模块链接
     */
    url?: string;
  }
}

/**
 * 类型名称：获取顶部导航列表
 *
 * @description 接口路径：/voltron/navigation/list
 * @description 接口分组：顶部导航模块 navigation
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronNavigationList {
  export interface Req {
    order?: string;
    orderField?: string;
    /**
     * 项目ID
     */
    projectId: string;
  }
  export interface Res {
    list?: ListItem[];
    total?: number;
  }
  export interface ListItem {
    ctime: string;
    id: number;
    mtime: string;
    /**
     * 导航名称
     */
    name: string;
    /**
     * 顺序
     */
    order: number;
    /**
     * 关联项目ID
     */
    projectId: string;
    /**
     * 链接地址
     */
    url: string;
    /**
     * 链接类型
     */
    urlType: number;
  }
}

/**
 * 类型名称：更新顶部导航
 *
 * @description 接口路径：/voltron/navigation/update
 * @description 接口分组：顶部导航模块 navigation
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronNavigationUpdate {
  export type Res = boolean;

  export interface Req {
    /**
     * 导航数据
     */
    navigationList: NavigationListItem[];
    /**
     * 项目ID
     */
    projectId: string;
  }
  export interface NavigationListItem {
    /**
     * 导航ID
     */
    id?: number;
    /**
     * 导航名
     */
    name?: string;
    /**
     * 链接
     */
    url?: string;
    /**
     * 链接类型， 0：外部链接，1：内部链接
     * @enum 0,1
     */
    urlType?: number;
  }
}

/**
 * 类型名称：创建批注
 *
 * @description 接口路径：/voltron/note/create
 * @description 接口分组：批注模块 note
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronNoteCreate {
  export type Res = boolean;

  export interface Req {
    /**
     * 关联组件ID
     */
    componentId?: string;
    /**
     * 批注内容
     */
    noteData: string;
    /**
     * 页面ID
     */
    pageId: string;
  }
}

/**
 * 类型名称：删除批注
 *
 * @description 接口路径：/voltron/note/delete
 * @description 接口分组：批注模块 note
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronNoteDelete {
  export type Res = boolean;

  export interface Req {
    /**
     * 批注ID
     */
    id: number;
  }
}

/**
 * 类型名称：获取批注列表
 *
 * @description 接口路径：/voltron/note/list
 * @description 接口分组：批注模块 note
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronNoteList {
  export interface Req {
    order?: string;
    orderField?: string;
    /**
     * 页面ID
     */
    pageId: string;
  }
  export interface Res {
    list?: ListItem[];
    total?: number;
  }
  export interface ListItem {
    /**
     * 组件ID
     */
    componentId: string;
    ctime: string;
    id: number;
    mtime: string;
    /**
     * 批注内容
     */
    noteData: string;
    /**
     * 页面ID
     */
    pageId: string;
  }
}

/**
 * 类型名称：更新批注
 *
 * @description 接口路径：/voltron/note/update
 * @description 接口分组：批注模块 note
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronNoteUpdate {
  export type Res = boolean;

  export interface Req {
    /**
     * 批注ID
     */
    id: number;
    /**
     * 批注内容
     */
    noteData: string;
  }
}

/**
 * 类型名称：创建页面
 *
 * @description 接口路径：/voltron/page/create
 * @description 接口分组：页面模块 page
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronPageCreate {
  export interface Req {
    /**
     * dslUrlBatchKey
     */
    dslUrlBatchKey: string;
    /**
     * 页面名称
     */
    name: string;
    /**
     * 项目ID
     */
    projectId: string;
  }
  export interface Res {
    /**
     * 页面创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 当前版本
     */
    currentVersion?: number;
    /**
     * DSL链接BatchKey
     */
    dslUrlBatchKey?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 页面名称
     */
    name?: string;
    /**
     * 页面ID
     */
    pageId?: string;
    /**
     * 项目ID
     */
    projectId?: string;
    /**
     * 是否显示菜单
     */
    showMenu?: number;
    /**
     * 页面更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：删除页面
 *
 * @description 接口路径：/voltron/page/delete
 * @description 接口分组：页面模块 page
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 20:31:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronPageDelete {
  export type Res = any;

  export interface Req {
    /**
     * 页面ID
     */
    pageId: string;
  }
}

/**
 * 类型名称：获取页面详情
 *
 * @description 接口路径：/voltron/page/detail
 * @description 接口分组：页面模块 page
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronPageDetail {
  export interface Req {
    pageId: string;
  }
  export interface Res {
    /**
     * 页面创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 当前版本
     */
    currentVersion?: number;
    /**
     * DSL链接BatchKey
     */
    dslUrlBatchKey?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 页面名称
     */
    name?: string;
    /**
     * 页面ID
     */
    pageId?: string;
    /**
     * 项目ID
     */
    projectId?: string;
    /**
     * 是否显示菜单
     */
    showMenu?: number;
    /**
     * 页面更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：获取页面列表
 *
 * @description 接口路径：/voltron/page/list
 * @description 接口分组：页面模块 page
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 20:31:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronPageList {
  /**
   * res
   */
  export type Res = ResItem[];

  export interface Req {
    /**
     * 项目ID
     */
    projectId: string;
  }
  export interface ResItem {
    /**
     * 页面创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 当前版本
     */
    currentVersion?: number;
    /**
     * DSL链接BatchKey
     */
    dslUrlBatchKey?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 页面名称
     */
    name?: string;
    /**
     * 页面ID
     */
    pageId?: string;
    /**
     * 项目ID
     */
    projectId?: string;
    /**
     * 是否显示菜单
     */
    showMenu?: number;
    /**
     * 页面更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：更新页面
 *
 * @description 接口路径：/voltron/page/update
 * @description 接口分组：页面模块 page
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronPageUpdate {
  export interface Req {
    /**
     * 页面版本
     */
    currentVersion?: number;
    /**
     * dslUrlBatchKey
     */
    dslUrlBatchKey?: string;
    /**
     * 页面名称
     */
    name?: string;
    /**
     * 页面ID
     */
    pageId: string;
    /**
     * 是否显示左侧菜单
     */
    showMenu?: number;
  }
  export interface Res {
    /**
     * 页面创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 当前版本
     */
    currentVersion?: number;
    /**
     * DSL链接BatchKey
     */
    dslUrlBatchKey?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 页面名称
     */
    name?: string;
    /**
     * 页面ID
     */
    pageId?: string;
    /**
     * 项目ID
     */
    projectId?: string;
    /**
     * 是否显示菜单
     */
    showMenu?: number;
    /**
     * 页面更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：获取页面版本列表
 *
 * @description 接口路径：/voltron/page/version/list
 * @description 接口分组：页面模块 page
 * 
 * @author openapi
 * @time 创建时间：2024-11-26 15:09:56
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronPageVersionList {
  export interface Req {
    /**
     * 页面ID
     */
    pageId: string;
  }
  export interface Res {
    pageInfo: PageInfo;
    pageVersionList: PageVersionListItem[];
  }
  export interface PageInfo {
    /**
     * 页面创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 当前版本
     */
    currentVersion?: number;
    /**
     * DSL链接BatchKey
     */
    dslUrlBatchKey?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 页面名称
     */
    name?: string;
    /**
     * 页面ID
     */
    pageId?: string;
    /**
     * 项目ID
     */
    projectId?: string;
    /**
     * 是否显示菜单
     */
    showMenu?: number;
    /**
     * 页面更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface PageVersionListItem {
    ctime: string;
    /**
     * DSL链接BatchKey
     */
    dslUrlBatchKey: string;
    id: number;
    mtime: string;
    /**
     * 页面ID
     */
    pageId: string;
    /**
     * 页面版本ID
     */
    versionId: string;
    /**
     * 版本号
     */
    versionNumber: number;
  }
}

/**
 * 类型名称：创建项目
 *
 * @description 接口路径：/voltron/project/create
 * @description 接口分组：项目模块 project
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronProjectCreate {
  export interface Req {
    /**
     * 自定义代码仓库分支
     */
    customCodeRepoBranch?: string;
    /**
     * 自定义代码仓库组件路径
     */
    customCodeRepoComponentPath?: string;
    /**
     * 自定义代码仓库
     */
    customCodeRepoSlug?: string;
    /**
     * 项目名称
     */
    name: string;
    /**
     * 项目平台
     */
    projectPlatform: string;
  }
  export interface Res {
    /**
     * 项目创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 自定义代码仓库分支
     */
    customCodeRepoBranch?: string;
    /**
     * 自定义代码仓库组件路径
     */
    customCodeRepoComponentPath?: string;
    /**
     * 自定义代码仓库
     */
    customCodeRepoSlug?: string;
    /**
     * 项目ID
     */
    id?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    /**
     * 是否公开
     */
    isPublic?: number;
    mtime?: string;
    /**
     * 项目名称
     */
    name?: string;
    /**
     * 项目ID
     */
    projectId?: string;
    /**
     * 项目平台
     */
    projectPlatform?: string;
    /**
     * 项目更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：删除项目
 *
 * @description 接口路径：/voltron/project/delete
 * @description 接口分组：项目模块 project
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronProjectDelete {
  export type Res = any;

  export interface Req {
    /**
     * 项目ID
     */
    projectId: string;
  }
}

/**
 * 类型名称：获取项目详情
 *
 * @description 接口路径：/voltron/project/detail
 * @description 接口分组：项目模块 project
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronProjectDetail {
  export interface Req {
    projectId: string;
  }
  export interface Res {
    /**
     * 项目创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 自定义代码仓库分支
     */
    customCodeRepoBranch?: string;
    /**
     * 自定义代码仓库组件路径
     */
    customCodeRepoComponentPath?: string;
    /**
     * 自定义代码仓库
     */
    customCodeRepoSlug?: string;
    /**
     * 项目ID
     */
    id?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    /**
     * 是否公开
     */
    isPublic?: number;
    mtime?: string;
    /**
     * 项目名称
     */
    name?: string;
    /**
     * 项目ID
     */
    projectId?: string;
    /**
     * 项目平台
     */
    projectPlatform?: string;
    /**
     * 项目更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：获取项目列表
 *
 * @description 接口路径：/voltron/project/list
 * @description 接口分组：项目模块 project
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronProjectList {
  /**
   * res
   */
  export type Res = ResItem[];

  export interface Req {
    /**
     * 项目编辑时间排序方式: 0-正序; 1-倒序; 默认倒序
     * @default 1
     * @enum 0,1
     */
    mTimeSortBy?: number;
    /**
     * 项目名搜索
     */
    name?: string;
    /**
     * 项目ID搜索
     */
    projectId?: string;
  }
  export interface ResItem {
    /**
     * 项目创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 自定义代码仓库分支
     */
    customCodeRepoBranch?: string;
    /**
     * 自定义代码仓库组件路径
     */
    customCodeRepoComponentPath?: string;
    /**
     * 自定义代码仓库
     */
    customCodeRepoSlug?: string;
    /**
     * 项目ID
     */
    id?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    /**
     * 是否公开
     */
    isPublic?: number;
    mtime?: string;
    /**
     * 项目名称
     */
    name?: string;
    /**
     * 项目ID
     */
    projectId?: string;
    /**
     * 项目平台
     */
    projectPlatform?: string;
    /**
     * 项目更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：编辑项目
 *
 * @description 接口路径：/voltron/project/update
 * @description 接口分组：项目模块 project
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronProjectUpdate {
  export interface Req {
    /**
     * 自定义代码仓库分支
     */
    customCodeRepoBranch?: string;
    /**
     * 自定义代码仓库组件路径
     */
    customCodeRepoComponentPath?: string;
    /**
     * 自定义代码仓库
     */
    customCodeRepoSlug?: string;
    /**
     * 是否公开
     * @enum 0,1
     */
    isPublic?: number;
    /**
     * 项目名称
     */
    name?: string;
    /**
     * 项目ID
     */
    projectId: string;
    /**
     * 项目平台
     */
    projectPlatform?: string;
  }
  export interface Res {
    /**
     * 项目创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 自定义代码仓库分支
     */
    customCodeRepoBranch?: string;
    /**
     * 自定义代码仓库组件路径
     */
    customCodeRepoComponentPath?: string;
    /**
     * 自定义代码仓库
     */
    customCodeRepoSlug?: string;
    /**
     * 项目ID
     */
    id?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    /**
     * 是否公开
     */
    isPublic?: number;
    mtime?: string;
    /**
     * 项目名称
     */
    name?: string;
    /**
     * 项目ID
     */
    projectId?: string;
    /**
     * 项目平台
     */
    projectPlatform?: string;
    /**
     * 项目更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：创建模板
 *
 * @description 接口路径：/voltron/template/create
 * @description 接口分组：模板模块 template
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronTemplateCreate {
  export interface Req {
    /**
     * 类别
     */
    category?: string;
    /**
     * 封面链接
     */
    coverUrl: string;
    /**
     * 模板名称
     */
    name: string;
    /**
     * 模板链接
     */
    templateUrl: string;
  }
  export interface Res {
    /**
     * 类别
     */
    category?: string;
    /**
     * 封面链接
     */
    coverUrl?: string;
    /**
     * 模板创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 模板ID
     */
    id?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 模板名称
     */
    name?: string;
    /**
     * 模板ID
     */
    templateId?: string;
    /**
     * 模板链接
     */
    templateUrl?: string;
    /**
     * 模板更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：删除模板
 *
 * @description 接口路径：/voltron/template/delete
 * @description 接口分组：模板模块 template
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 20:31:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronTemplateDelete {
  export type Res = any;

  export interface Req {
    /**
     * 模板ID
     */
    templateId: string;
  }
}

/**
 * 类型名称：获取模板详情
 *
 * @description 接口路径：/voltron/template/detail
 * @description 接口分组：模板模块 template
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 16:01:59
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronTemplateDetail {
  export interface Req {
    templateId: string;
  }
  export interface Res {
    /**
     * 类别
     */
    category?: string;
    /**
     * 封面链接
     */
    coverUrl?: string;
    /**
     * 模板创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 模板ID
     */
    id?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 模板名称
     */
    name?: string;
    /**
     * 模板ID
     */
    templateId?: string;
    /**
     * 模板链接
     */
    templateUrl?: string;
    /**
     * 模板更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：获取模板列表
 *
 * @description 接口路径：/voltron/template/list
 * @description 接口分组：模板模块 template
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 20:31:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronTemplateList {
  /**
   * res
   */
  export type Res = ResItem[];

  export interface Req {
    /**
     * 模板名搜索
     */
    name?: string;
    /**
     * 模板ID搜索
     */
    templateId?: string;
  }
  export interface ResItem {
    /**
     * 类别
     */
    category?: string;
    /**
     * 封面链接
     */
    coverUrl?: string;
    /**
     * 模板创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 模板ID
     */
    id?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 模板名称
     */
    name?: string;
    /**
     * 模板ID
     */
    templateId?: string;
    /**
     * 模板链接
     */
    templateUrl?: string;
    /**
     * 模板更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：编辑模板
 *
 * @description 接口路径：/voltron/template/update
 * @description 接口分组：模板模块 template
 * 
 * @author openapi
 * @time 创建时间：2024-11-21 20:31:50
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace PostVoltronTemplateUpdate {
  export interface Req {
    /**
     * 类别
     */
    category?: string;
    /**
     * 封面链接
     */
    coverUrl?: string;
    /**
     * 模板名称
     */
    name?: string;
    /**
     * 模板ID
     */
    templateId: string;
    /**
     * 模板链接
     */
    templateUrl?: string;
  }
  export interface Res {
    /**
     * 类别
     */
    category?: string;
    /**
     * 封面链接
     */
    coverUrl?: string;
    /**
     * 模板创建者
     */
    creator?: string;
    creatorInfo?: CreatorInfo;
    ctime?: string;
    /**
     * 模板ID
     */
    id?: string;
    /**
     * 是否当前用户创建
     */
    isOwner?: number;
    mtime?: string;
    /**
     * 模板名称
     */
    name?: string;
    /**
     * 模板ID
     */
    templateId?: string;
    /**
     * 模板链接
     */
    templateUrl?: string;
    /**
     * 模板更新者
     */
    updater?: string;
    updaterInfo?: UpdaterInfo;
  }
  export interface CreatorInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
  export interface UpdaterInfo {
    adAccount: string;
    avatarUrl: string;
    deptCode: string;
    deptCodeSeq: string;
    deptName: string;
    deptNameSeq: string;
    nickName: string;
  }
}

/**
 * 类型名称：获取当前用户信息
 *
 * @description 接口路径：/voltron/user/current-user
 * @description 接口分组：用户
 * 
 * @author openapi
 * @time 创建时间：2025-05-29 14:55:58
 * @time 更新时间：2025-05-29 15:11:23
 * @version v20250529.05
 */
export namespace GetVoltronUserCurrentUser {
  export type Res = any;
}
